config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users

  resources :users, only: :show do
    resources :posts, expect: :index
  end
  resources :posts, only: :index


  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  scope :find_newest_article, -> { order(created_at: :desc).limit(5)}
  belongs_to :category
  belongs_to :user
validates :title, presence: true, length: { maximum: 50 }
validates :body,  presence: true, length: { maximum: 2000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

has_one_attached :avatar
has_many :posts
  validates :name, presence: true, length: { maximum: 30 }
  validates :description,  presence: true, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :avatar])
  end

  private

  def set_search
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(4)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy]

  def index
      # @posts = Post.all.order(created_at: :desc)でも可
      @new_posts = Post.find_newest_article
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.attributes = {
      user_id: current_user.id
    }
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: "ブログを登録しました。"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_post_path(current_user, @post), notice: "ブログを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "ブログを削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/header" %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <%= render "shared/flash" %>
        </div>
      </div>
      
      <div class="row">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model:[current_user, post] , local: true do |form| %>
  <%= render "shared/errors", obj: post %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name , { include_blank: "カテゴリーを選択して下さい" },  { class: "form-control" } %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to '戻る', :back, class: "btn btn-secondary" %>
<% end %>

app/views/posts/edit.html.erb
  <div class="col-md-10 offset-md-1 mt-3">
    <h2 class="text-center">ブログ編集</h2>
    <%= render 'form', post: @post %>
  </div>

app/views/posts/index.html.erb
<div class="col-md-8">
  <% @posts.each do |post| %>
    <div class="article">
      <h2>タイトル：<%= post.title %></h2>
      <p>著者：<%= link_to post.user.name, post.user %></p>
      <p>作成日：<%= post.created_at %></p>
      <p><%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", user_post_path(post.user, post), class: "btn btn-info" %></p>
    </div>
  <% end %>
<%= paginate @posts %>
</div>
<div class="col-md-4">
  <div class="list-group">
    <% @new_posts.each do |post| %>
    <%= link_to post.title, user_post_path(post.user, post), class: "list-group-item" %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">ブログ登録</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <h2><%= @post.title %></h2>
  <p>投稿日:<%= @post.created_at %></p>
  <p>カテゴリー:<%= @post.category&.name %></p>
  <hr>
  <%= simple_format(@post.body) %>
  <hr>
  <%= link_to "編集", edit_user_post_path(@post.user, @post), class: "btn btn-success" %>
  <%= button_tag "削除", class: "btn btn-warning", data: { toggle: "modal", target: "#delete-post" } %>
  <%= link_to "戻る", posts_path, class: "btn btn-secondary" %>
</div>

  <div class="modal fade" id="delete-post">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">ブログ削除</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p><%= "#{@post.title}を削除しますか？" %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
          <%= link_to "削除", user_post_path(@post.user, @post), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "My Blog", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "New Post", new_user_post_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "設定変更", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%= search_form_for @q, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :title_or_body_cont, class: "form-control mr-sm-2" %>
      <%= f.submit "検索", class: "btn btn-info my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/users/show.html.erb
<div class="col-md-8">
  <% @posts.each do |post| %>
    <div class="article">
      <h2>タイトル：<%= post.title %></h2>
      <p>作成日：<%= post.created_at %></p>
      <p><%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", user_post_path(@user, post), class: "btn btn-info" %></p>
    </div>
  <% end %>
</div>
<div class="col-md-4">
  <div class="card">
    <%= image_tag @user.avatar, class: "card-img-top", alt: "著者イメージ" %>
    <div class="card-body">
      <h3>著者名：<%= @user.name %></h3>
      <p>詳細：<%= @user.description %></p>
    </div>
  </div>
</div>